[meta]
# site title, show in <title>
title = "一条咸鱼"

# subtitle, words after title, in description
subtitle = "doozz"

# print in html <meta>
keyword = "pugo,golang,static,site,generator,一条咸鱼,doozz"

# print in html <meta>
desc = "一条咸鱼,doozz"

# build links for feed, sitemap
domain = "118.24.112.78"

# root path for site# if empty, build as http://{domain}/
root = "http://118.24.112.78/doo/"

# cover page for homepage
cover = "@media/cover.jpg"

# global language,
# its used in global posts and themes, unless pages set lang
lang = "zh"

[[nav]]
link = "/"
title = "Archive"
i18n = "archive"
# set nav to active status
hover = "archive"
blank = false




[[author]]
name = "doozz"
email = ""
url = "http://118.24.112.78/"
avatar = "@media/author.png"
bio = "the robot of pugo, who generates all default contents."

# comment settings
# please only set one value
# if multi values, it prints all comment iframes
[comment]
# disqus site name
disqus = ""
# duoshuo short name
duoshuo = ""

# analytics settings
# please only set one value
# if multi values, it prints all analytics codes
[analytics]
# google analytics, need as UA-XXXXX-Y
google = ""
# baidu analytics, need hash-code in hm.js?hash-code
baidu = ""
